name: Install OneClickInstall Docker

on:
  push:
    branches:
      - develop

jobs:
  testing:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:         
          - distr: onlyoffice
            os: centos7
            name: "CentOS 7"

          - distr: onlyoffice
            os: centos8s
            name: "CentOS 8 Stream"         

          - distr: onlyoffice
            os: centos9s
            name: "CentOS 9 Stream"               

          - distr: onlyoffice
            os: debian10
            name: "Debian 10"

          - distr: onlyoffice
            os: debian11
            name: "Debian 11"

          - distr: onlyoffice
            os: bookworm64
            name: "Debian 12"

          - distr: onlyoffice
            os: bionic64
            name: "Ubuntu 18.04"            

          - distr: onlyoffice
            os: ubuntu2004
            name: "Ubuntu 20.04"

          - distr: onlyoffice
            os: ubuntu2204
            name: "Ubuntu 22.04"
    steps:
      - name: Print Hello Message
        run: echo "Hello world from Testing job"

