name: Install OneClickInstall Docker

on:
  push:
    branches:
      - develop

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello Message
        run: echo "Hello world from Testing job"
###
      - name: Simulate failure
        run: exit 1


